[[troubleshooting]]
= Troubleshooting

This chapter contains common troubleshooting steps. Additionally, there is a section for xref::troubleshooting/faqs.adoc[FAQs] (Frequently Asked Questions) where you might find answers to your problems.

[[troubleshooting-debug-logging]]
== Debug Logging

=== For `@mathix420/graphql`

`@mathix420/graphql` uses the https://www.npmjs.com/package/debug[`debug`] library for debug-level logging. You can turn on all debug logging by setting the environment variable `DEBUG` to `@mathix420/graphql:*` when running. For example:

[source, bash, indent=0]
----
DEBUG=@mathix420/graphql:* node src/index.js
----

Alternatively, if you are debugging a particular functionality, you can specify a number of namespaces to isolate certain log lines:

1. `@mathix420/graphql:*` - Logs all
2. `@mathix420/graphql:auth` - Logs the status of authorization header and token extraction, and decoding of JWT
3. `@mathix420/graphql:graphql` - Logs the GraphQL query and variables
4. `@mathix420/graphql:execute` - Logs the Cypher and Cypher paramaters before execution, and summary of execution

=== For `@mathix420/introspector`

`@mathix420/introspector` has its own debug logging namespace and you can turn on logging for it with:

[source, bash, indent=0]
----
DEBUG=@mathix420/introspector node src/index.js
----

Read more about the xref::introspector.adoc[introspector].

[[troubleshooting-query-tuning]]
== Query Tuning

Hopefully you won't need to perform any query tuning, but if you do, the Neo4j GraphQL Library allows you to set the full array of query options on construction of the library.

You can read more about the available query options at https://neo4j.com/docs/cypher-manual/current/query-tuning/query-options/#cypher-query-options.

_Please only set these options if you know what you are doing._

For example, in order to set the Cypher runtime to "interpreted":

[source, javascript, indent=0]
----
const { Neo4jGraphQL, CypherRuntime } = require("@mathix420/graphql");
const neo4j = require("neo4j-driver");
const { ApolloServer } = require("apollo-server");

const typeDefs = `
    type Movie {
        title: String!
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("neo4j", "password")
);

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    driver,
    config: {
        queryOptions: {
            runtime: CypherRuntime.INTERPRETED,
        },
    },
});

const server = new ApolloServer({
    schema: neoSchema.schema,
    context: ({ req }) => ({ req }),
});

server.listen().then(({ url }) => {
  console.log(`Server ready at ${url}`);
});
----
